Projekt/Models/Post.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Projekt.Models
{
    public class Post
    {
        [Key]
        public int ID { get; set; }
        [Required]
        [Display(Name = "Title")]
        [StringLength(100, MinimumLength = 2, ErrorMessage = "Title cannot be longer than 100 characters.")]
        public string Title { get; set; }
        [Required]
        [Display(Name = "Text")]
        [StringLength(5000, MinimumLength = 2, ErrorMessage = "Title cannot be longer than 5000 characters.")]
        public string Text { get; set; }
        public string Image { get; set; }
        public int ProfileId { get; set; }


        public virtual List<Comment> Comments { get; set; }
        public virtual Profil Profil { get; set; }
    }
}

Projekt/Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Projekt.DAL;
using Projekt.Models;

namespace Projekt.Controllers
{
    public class CommentsController : Controller
    {
        private SiteContext db = new SiteContext();

        // GET: Comments
        public ActionResult Index()
        {
            var comments = db.Comments.Include(c => c.Post);
            return View(comments.ToList());
        }

        // GET: Comments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        // GET: Comments/Create
        public ActionResult Create()
        {
            ViewBag.PostID = new SelectList(db.Posts, "ID", "Title");
            return View();
        }

        // POST: Comments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost] 
        public ActionResult Create([Bind(Include = "ID,Text,PostID,ProfilID")] Comment comment)
        {
            if (ModelState.IsValid)
            {
                Profil myProfile = db.Profiles.Single(p => p.Login == User.Identity.Name);
                comment.Profil = myProfile;
                db.Comments.Add(comment);
                db.SaveChanges();
                return RedirectToAction("Details", "Posts", new { id = comment.PostID});
            }

            ViewBag.PostID = new SelectList(db.Posts, "ID", "Title", comment.PostID);
            return View(comment);
        }

        // GET: Comments/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            ViewBag.PostID = new SelectList(db.Posts, "ID", "Title", comment.PostID);
            return View(comment);
        }

        // POST: Comments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Text,PostID,ProfilID")] Comment comment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(comment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", "Posts", new { id = comment.PostID });
            }
            ViewBag.PostID = new SelectList(db.Posts, "ID", "Title", comment.PostID);
            return View(comment);
        }

        // GET: Comments/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            db.Comments.Remove(comment);
            db.SaveChanges();
            return RedirectToAction("Details", "Posts", new { id = comment.PostID });
        }

        // POST: Comments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Comment comment = db.Comments.Find(id);
            db.Comments.Remove(comment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Projekt/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList;
using Projekt.DAL;
using Projekt.Models;

namespace Projekt.Controllers
{
    public class PostsController : Controller
    {
        private SiteContext db = new SiteContext();

        // GET: Posts
        public ActionResult Index(string sortPosts, string searchString, string currentFilter, int? page)
        {
            ViewBag.CurrentSort = sortPosts;
            ViewBag.TitleSortParm = String.IsNullOrEmpty(sortPosts) ? "Title_desc" : "";
            ViewBag.TextSortParm = String.IsNullOrEmpty(sortPosts) ? "Text_desc" : "";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var posts = from s in db.Posts
                        select s;

            if (!String.IsNullOrEmpty(searchString))
            {
                posts = posts.Where(s => s.Title.Contains(searchString));
            }
            switch (sortPosts)
            {

                case "Title_desc":
                    posts = posts.OrderByDescending(s => s.Title);
                    break;
                case "Text_desc":
                    posts = posts.OrderByDescending(s => s.Title);
                    break;
                default:
                    posts = posts.OrderBy(s => s.ID);
                    break;
            }
            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(posts.ToPagedList(pageNumber, pageSize));
        }

        // GET: Posts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }
         
        // GET: Posts/Create
        public ActionResult Create()
        {
            Profil myProfil = db.Profiles.Single(p => p.Login == User.Identity.Name);
            ViewBag.Posts = myProfil.Posts.ToList();
            return View();
        }

        // POST: Posts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Title,Text,Image, ProfileId")] Post post)
        {
            if (ModelState.IsValid)
            {
                Profil myProfile = db.Profiles.Single(p => p.Login == User.Identity.Name);
                post.Profil = myProfile;
                 
                db.Posts.Add(post);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(post);
        }

        // GET: Posts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }
         
        // POST: Posts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Title,Text,Image, ProfileId")] Post post)
        {
            if (ModelState.IsValid)
            {
                db.Entry(post).State = EntityState.Modified; 
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(post);
        }

        // GET: Posts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        // POST: Posts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Post post = db.Posts.Find(id);
            db.Posts.Remove(post);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Projekt/Views/Posts/Create.cshtml
@model Projekt.Models.Post

@{
    ViewBag.Title = "Create";
}

<h2>Utworz nowy post</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Post</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", new { area = "" }, new { @class = "btn btn-primary" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Projekt/Views/Posts/Delete.cshtml
@model Projekt.Models.Post

@{
    ViewBag.Title = "Delete";
}

<h2>Usun</h2>

<h3>Jestes pewien, ze chcesz usunac post</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Text)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Text)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index", new { area = "" }, new { @class = "btn btn-primary" })
        </div>
    }
</div>

Projekt/Views/Posts/Details.cshtml
@model Projekt.Models.Post

@{
    ViewBag.Title = "Details";
}

<h2>Post</h2>

<div>
    <hr />
    <div class="row">

        <h3> 
            @Html.DisplayFor(model => model.Title)
        </h3>

        <h4>
            @Html.DisplayFor(model => model.Text)
        </h4>

    <br />
    <hr />

    <div>
        <h5>Komentarze</h5>
        @foreach (var item in Model.Comments)
        {
            <div>
                @Html.DisplayFor(modelItem => item.Text)
            </div>
            <br /> 
            if (User.Identity.Name == item.Profil.Login)
            {
                @Html.ActionLink("Usun", "Delete", "Comments", new { id = item.ID }, new { @class = "btn btn-danger btn-sm" })
                @Html.ActionLink("Edytuj", "Edit", "Comments", new { id = item.ID }, new { @class = "btn btn-info btn-sm" })
                <br />
            }
                <hr />
            }
        </div>

    @using (Html.BeginForm("Create", "Comments"))
    {


        @Html.Hidden("PostID", Model.ID);


    }
    @if (Request.IsAuthenticated)
    {
        @Html.ActionLink("Dodaj Komentarz", "Create", "Comments", new { area = "" }, new { @class = "btn btn-success btn-sm" })
    }
</div>
<br />
<br />
<br />
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }, new { @class = "btn btn-info" }) |
    @Html.ActionLink("Back to List", "Index", new { area = "" }, new { @class = "btn btn-primary" })
</p>
</div>

Projekt/Views/Posts/Edit.cshtml
@model Projekt.Models.Post

@{
    ViewBag.Title = "Edit";
}



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Post</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", new { area = "" }, new { @class = "btn btn-info" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Projekt/Views/Posts/Fav.cshtml
@model IEnumerable<Projekt.Models.Fav>

@{
    ViewBag.Title = "Fav";
}

<h2>Fav</h2>

<table class="table">
    <tr>
        <th>
            Favorite post
        </th>
        <th>
            Pphoto
        </th>
        <th>
            Delete
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @item.Post.Title
            </td>
            <th>
                <img src="~/Photo/@item.Photo" alt="" height="100px" width="100px">
            </th>
            <td>
                @Html.ActionLink("Delete", "DeleteFavorite", "Posts", new { id = item.ID }, null)
            </td>
        </tr>
    }
</table>

Projekt/Views/Posts/Index.cshtml
@model PagedList.IPagedList<Projekt.Models.Post>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Index";
}
<h2>Wszystkie posty</h2>
<br />
<br />
@using (Html.BeginForm("Index", "Posts", FormMethod.Get))
{
    <p>
         @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { @class = "form-control", @placeholder = "Wpisz..." })
        <input type="submit" value="Szukaj" class="btn btn-primary"/>
    </p>
}
@*<table class="table">
    <tr>*@
        <button class="btn btn-light">
            @Html.ActionLink("Title", "Index", new { sortPosts = ViewBag.TitleSortParm, currentFilter = ViewBag.CurrentFilter })
        </button>
        @*<th>
            Text
        </th>
        <th></th>

    </tr>*@
<div class="row" mt-5 md-2>
    @foreach (var item in Model)
    {
        <div class="col-lg-4">
            <h3>
                @Html.DisplayFor(modelItem => item.Title)
            </h3>
            <h4>
                @Html.DisplayFor(modelItem => item.Text)
            </h4>

                @if (User.Identity.Name == item.Profil.Login)
                {
                    <p>

                        @Html.ActionLink("Edytuj", "Edit", new { id = item.ID }, new { @class = "btn btn-info" })
                        @Html.ActionLink("Usun", "Delete", new { id = item.ID }, new { @class = "btn btn-danger" })

                    </p>
                }
                @*@Html.ActionLink("Like", "Add", new { id = item.ID })*@
                @Html.ActionLink("Details", "Details", new { id = item.ID }, new { @class = "btn btn-primary" })
                </div>

                }
    </div>
                <br />
                <br />
                @if (Request.IsAuthenticated)
                {
                    <p>
                        @Html.ActionLink("Utworz nowy", "Create", new { area = "" }, new { @class = "btn btn-success" })
                    </p>
                }

                <br />
                Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

                @Html.PagedListPager(Model, page => Url.Action("Index",
                    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))